-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.auction_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid,
  title character varying NOT NULL,
  description text,
  scheduled_start timestamp with time zone,
  scheduled_end timestamp with time zone,
  min_items integer DEFAULT 10 CHECK (min_items > 0),
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'active'::character varying, 'completed'::character varying, 'canceled'::character varying]::text[])),
  banner_image text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auction_events_pkey PRIMARY KEY (id),
  CONSTRAINT auction_events_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id)
);
CREATE TABLE public.auction_watchers (
  auction_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auction_watchers_pkey PRIMARY KEY (auction_id, user_id),
  CONSTRAINT auction_watchers_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT auction_watchers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.auctions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid,
  title character varying NOT NULL,
  description text NOT NULL,
  reserve numeric DEFAULT 0 CHECK (reserve >= 0::numeric),
  starting_bid numeric DEFAULT 0 CHECK (starting_bid >= 0::numeric),
  bid_increment numeric DEFAULT 1.00 CHECK (bid_increment > 0::numeric),
  buy_now_price numeric CHECK (buy_now_price > 0::numeric),
  start_at timestamp with time zone DEFAULT now(),
  end_at timestamp with time zone NOT NULL,
  category character varying NOT NULL,
  condition character varying CHECK (condition::text = ANY (ARRAY['new'::character varying, 'like_new'::character varying, 'excellent'::character varying, 'good'::character varying, 'fair'::character varying, 'poor'::character varying]::text[])),
  brand character varying,
  model character varying,
  image_url text,
  image_urls jsonb DEFAULT '[]'::jsonb,
  location character varying DEFAULT 'Singapore'::character varying,
  shipping_method character varying CHECK (shipping_method::text = ANY (ARRAY['pickup'::character varying, 'local'::character varying, 'nationwide'::character varying, 'both'::character varying]::text[])),
  shipping_cost numeric CHECK (shipping_cost >= 0::numeric),
  shipping_included boolean DEFAULT false,
  shipping_notes text,
  return_policy text,
  return_conditions text,
  require_verified_phone boolean DEFAULT false,
  require_min_rating boolean DEFAULT false,
  min_rating numeric DEFAULT 0 CHECK (min_rating >= 0::numeric AND min_rating <= 5::numeric),
  block_unpaid_buyers boolean DEFAULT false,
  additional_requirements text,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'scheduled'::character varying, 'active'::character varying, 'completed'::character varying, 'canceled'::character varying, 'suspended'::character varying]::text[])),
  event_id uuid,
  scheduled boolean DEFAULT false,
  featured boolean DEFAULT false,
  views integer DEFAULT 0 CHECK (views >= 0),
  watchers_count integer DEFAULT 0 CHECK (watchers_count >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auctions_pkey PRIMARY KEY (id),
  CONSTRAINT auctions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id),
  CONSTRAINT auctions_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.auction_events(id)
);
CREATE TABLE public.auto_bids (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  bidder_id uuid,
  max_amount numeric NOT NULL CHECK (max_amount > 0::numeric),
  increment numeric NOT NULL CHECK (increment > 0::numeric),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auto_bids_pkey PRIMARY KEY (id),
  CONSTRAINT auto_bids_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT auto_bids_bidder_id_fkey FOREIGN KEY (bidder_id) REFERENCES public.users(id)
);
CREATE TABLE public.bids (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  bidder_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  is_auto_bid boolean DEFAULT false,
  max_auto_bid numeric,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bids_pkey PRIMARY KEY (id),
  CONSTRAINT bids_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT bids_bidder_id_fkey FOREIGN KEY (bidder_id) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_confirmations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  buyer_id uuid,
  seller_id uuid,
  confirmed boolean DEFAULT false,
  confirmed_at timestamp with time zone,
  tracking_number text,
  delivery_method character varying,
  delivery_notes text,
  delivery_photos jsonb DEFAULT '[]'::jsonb,
  auto_confirm_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_confirmations_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_confirmations_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT delivery_confirmations_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(id),
  CONSTRAINT delivery_confirmations_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id)
);
CREATE TABLE public.disputes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  opener_id uuid,
  respondent_id uuid,
  reason text NOT NULL,
  category character varying DEFAULT 'other'::character varying CHECK (category::text = ANY (ARRAY['item_not_received'::character varying, 'item_not_as_described'::character varying, 'payment_issue'::character varying, 'shipping_issue'::character varying, 'other'::character varying]::text[])),
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'investigating'::character varying, 'awaiting_response'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  resolution text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  evidence_urls jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_id uuid,
  type character varying DEFAULT 'general'::character varying CHECK (type::text = ANY (ARRAY['item_not_received'::character varying, 'item_not_as_described'::character varying, 'payment_issue'::character varying, 'shipping_issue'::character varying, 'fraudulent_activity'::character varying, 'general'::character varying]::text[])),
  description text,
  resolution_type character varying CHECK (resolution_type::text = ANY (ARRAY['refund_buyer'::character varying, 'release_to_seller'::character varying, 'partial_refund'::character varying, 'no_action'::character varying]::text[])),
  messages jsonb DEFAULT '[]'::jsonb,
  stripe_dispute_id text,
  response_due_at timestamp with time zone,
  escalated_at timestamp with time zone,
  CONSTRAINT disputes_pkey PRIMARY KEY (id),
  CONSTRAINT disputes_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id),
  CONSTRAINT disputes_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT disputes_opener_id_fkey FOREIGN KEY (opener_id) REFERENCES public.users(id),
  CONSTRAINT disputes_respondent_id_fkey FOREIGN KEY (respondent_id) REFERENCES public.users(id),
  CONSTRAINT disputes_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.escrow_holds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  auction_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'released'::character varying, 'disputed'::character varying, 'expired'::character varying]::text[])),
  hold_until timestamp with time zone NOT NULL,
  auto_release boolean DEFAULT true,
  buyer_confirmed boolean DEFAULT false,
  buyer_confirmed_at timestamp with time zone,
  dispute_opened boolean DEFAULT false,
  release_reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT escrow_holds_pkey PRIMARY KEY (id),
  CONSTRAINT escrow_holds_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT escrow_holds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.followers (
  follower_id uuid NOT NULL,
  followed_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT followers_pkey PRIMARY KEY (follower_id, followed_user_id),
  CONSTRAINT followers_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.users(id),
  CONSTRAINT followers_followed_user_id_fkey FOREIGN KEY (followed_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notification_preferences (
  user_id uuid NOT NULL,
  email_new_bid boolean DEFAULT true,
  email_outbid boolean DEFAULT true,
  email_auction_ending boolean DEFAULT true,
  email_auction_won boolean DEFAULT true,
  email_payment_received boolean DEFAULT true,
  push_new_bid boolean DEFAULT true,
  push_outbid boolean DEFAULT true,
  push_auction_ending boolean DEFAULT true,
  sms_auction_won boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  type character varying NOT NULL,
  title character varying,
  message text NOT NULL,
  link text,
  data jsonb DEFAULT '{}'::jsonb,
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.outcomes (
  auction_id uuid NOT NULL,
  winner_id uuid,
  final_price numeric,
  winning_bid_id uuid,
  payment_intent_id text,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  captured_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT outcomes_pkey PRIMARY KEY (auction_id),
  CONSTRAINT outcomes_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT outcomes_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.users(id),
  CONSTRAINT outcomes_winning_bid_id_fkey FOREIGN KEY (winning_bid_id) REFERENCES public.bids(id)
);
CREATE TABLE public.payment_step_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  step character varying NOT NULL,
  status character varying NOT NULL,
  stripe_event_id text,
  stripe_response jsonb,
  error_message text,
  retry_count integer DEFAULT 0,
  processed_by text,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_step_logs_pkey PRIMARY KEY (id),
  CONSTRAINT payment_step_logs_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  auction_id uuid,
  intent_id text UNIQUE,
  stripe_payment_intent_id text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying DEFAULT 'SGD'::character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'succeeded'::character varying, 'failed'::character varying, 'canceled'::character varying, 'requires_confirmation'::character varying, 'requires_action'::character varying, 'requires_capture'::character varying]::text[])),
  fee_applied numeric DEFAULT 0 CHECK (fee_applied >= 0::numeric),
  platform_fee numeric DEFAULT 0 CHECK (platform_fee >= 0::numeric),
  subscription_discount numeric DEFAULT 0 CHECK (subscription_discount >= 0::numeric),
  payment_method character varying,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stripe_transfer_id text,
  capture_method character varying DEFAULT 'automatic'::character varying,
  application_fee_amount numeric DEFAULT 0,
  payment_step character varying DEFAULT 'pre_authorized'::character varying CHECK (payment_step::text = ANY (ARRAY['pre_authorized'::character varying, 'captured'::character varying, 'in_escrow'::character varying, 'released'::character varying, 'disputed'::character varying, 'completed'::character varying]::text[])),
  platform_fee_rate numeric DEFAULT 5.00,
  platform_fee_amount numeric DEFAULT 0,
  stripe_fee_amount numeric DEFAULT 0,
  net_amount numeric DEFAULT 0,
  pre_authorized_at timestamp with time zone,
  captured_at timestamp with time zone,
  escrowed_at timestamp with time zone,
  release_scheduled_at timestamp with time zone,
  released_at timestamp with time zone,
  payment_method_id text,
  payment_method_type character varying,
  last_four character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payments_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid,
  auction_id uuid,
  payment_id uuid,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  status character varying DEFAULT 'on_hold'::character varying CHECK (status::text = ANY (ARRAY['on_hold'::character varying, 'processing'::character varying, 'paid'::character varying, 'failed'::character varying, 'canceled'::character varying, 'pending'::character varying, 'reversed'::character varying]::text[])),
  stripe_transfer_id text,
  released_at timestamp with time zone,
  hold_expires_at timestamp with time zone,
  hold_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gross_amount numeric,
  platform_fee numeric,
  stripe_fee numeric DEFAULT 0,
  net_amount numeric,
  stripe_payout_id text,
  scheduled_for timestamp with time zone,
  processed_at timestamp with time zone,
  destination_account text,
  failure_reason text,
  retry_count integer DEFAULT 0,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id),
  CONSTRAINT payouts_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT payouts_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  reviewer_id uuid,
  target_user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id),
  CONSTRAINT ratings_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT ratings_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.stripe_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  stripe_account_id text NOT NULL UNIQUE,
  account_type character varying DEFAULT 'express'::character varying CHECK (account_type::text = ANY (ARRAY['express'::character varying, 'custom'::character varying, 'standard'::character varying]::text[])),
  details_submitted boolean DEFAULT false,
  payouts_enabled boolean DEFAULT false,
  charges_enabled boolean DEFAULT false,
  verification_status character varying DEFAULT 'unverified'::character varying CHECK (verification_status::text = ANY (ARRAY['unverified'::character varying, 'pending'::character varying, 'verified'::character varying, 'rejected'::character varying]::text[])),
  requirements_pending jsonb DEFAULT '[]'::jsonb,
  requirements_eventually_due jsonb DEFAULT '[]'::jsonb,
  requirements_currently_due jsonb DEFAULT '[]'::jsonb,
  country character varying DEFAULT 'SG'::character varying,
  default_currency character varying DEFAULT 'SGD'::character varying,
  business_type character varying,
  business_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  monthly_fee numeric NOT NULL CHECK (monthly_fee >= 0::numeric),
  platform_fee_rate numeric DEFAULT 5.00 CHECK (platform_fee_rate >= 0::numeric AND platform_fee_rate <= 100::numeric),
  benefits ARRAY,
  max_active_auctions integer,
  featured_listings_per_month integer DEFAULT 0,
  priority_support boolean DEFAULT false,
  analytics_access boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  plan_name character varying,
  price numeric,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'canceled'::character varying, 'expired'::character varying, 'suspended'::character varying]::text[])),
  stripe_subscription_id text UNIQUE,
  stripe_customer_id text,
  auto_renew boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  user_id uuid NOT NULL,
  username character varying NOT NULL UNIQUE,
  first_name character varying,
  last_name character varying,
  profile_image text,
  bio text,
  rating_average numeric DEFAULT 0 CHECK (rating_average >= 0::numeric AND rating_average <= 5::numeric),
  rating_count integer DEFAULT 0 CHECK (rating_count >= 0),
  followers_count integer DEFAULT 0 CHECK (followers_count >= 0),
  following_count integer DEFAULT 0 CHECK (following_count >= 0),
  badges ARRAY,
  location character varying,
  preferred_language character varying DEFAULT 'en'::character varying,
  timezone character varying DEFAULT 'Asia/Singapore'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone character varying,
  email character varying UNIQUE,
  kyc_status character varying DEFAULT 'pending'::character varying CHECK (kyc_status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'rejected'::character varying]::text[])),
  role character varying DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['user'::character varying, 'admin'::character varying, 'moderator'::character varying]::text[])),
  is_pro boolean DEFAULT false,
  subscription_plan character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stripe_account_id text,
  stripe_onboarding_complete boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);